mysite/urls.py
from django.conf.urls import patterns, include, url

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('control_inventario.app',
    url(r'^$', 'auth.views.index', name='index'),
    url(r'^usuario/change-pass$', 'auth.views.change_pass', name='change_pass'),
   #login
    url(r'^ingresar/$','auth.views.ingresar', name='ingresar'),
    url(r'^cerrar/$','auth.views.cerrar_session', name='cerrar'),
   # urls-empresa
    url(r'^empresa/$', 'empresa.views.empresa', name='empresa'),
    url(r'^empresa/del$', 'empresa.views.del_empresa', name='del_empresa'),
    url(r'^select-empresa$', 'empresa.views.select_empresa', name='select_empresa'),
    url(r'^select-periodo$', 'empresa.views.select_periodo', name='select_periodo'),
   # urls-categoria
    url(r'^categorias/$', 'categoria.views.categoria', name='categoria'),
    url(r'^categorias/del$', 'categoria.views.del_categoria', name='del_categoria'),
   # urls-productos
    url(r'^productos/$', 'producto.views.producto', name='producto'),
    url(r'^productos/del$', 'producto.views.del_producto', name='del_producto'),
   # urls-proveedor
    url(r'^proveedor/$', 'proveedor.views.proveedor', name='proveedor'),
    url(r'^proveedor/del$', 'proveedor.views.del_proveedor', name='del_proveedor'),
   # urls-cliente
    url(r'^cliente/$', 'cliente.views.cliente', name='cliente'),
    url(r'^cliente/del$', 'cliente.views.del_cliente', name='del_cliente'),
   # urls-usuario
    url(r'^usuario/$', 'usuario.views.usuario', name='usuario'),
    url(r'^usuario/del$', 'usuario.views.del_usuario', name='del_usuario'),
    # url(r'^datos-usuario$', 'usuario.views.datos_usuario', name='datos_usuario'),
   # urls-inventario
    url(r'^inventario/$', 'inventario.views.inventario_inicial', name='inventario'),
    url(r'^inventario-inicial/$', 'inventario.views.inventario_inicial_consulta', name='inventario'),
   # urls-salida de mercancia
    url(r'^salida/$', 'salida_mercancia.views.salida_mercancia', name='salida_mercancia'),
    url(r'^salida/del$', 'salida_mercancia.views.del_venta', name='del_venta'),
    url(r'^salida/add$', 'salida_mercancia.views.add_salida_mercancia', name='add_salida_mercancia'),
    url(r'^salida/detalles$', 'salida_mercancia.views.detalle_venta', name='detalle_venta'),
   # urls-entrada de mercancia
    url(r'^entrada/$', 'entrada_mercancia.views.entrada_mercancia', name='entrada_mercancia'),
    url(r'^entrada/add$', 'entrada_mercancia.views.add_entrada_mercancia', name='add_entrada_mercancia'),
    url(r'^entrada/del$', 'entrada_mercancia.views.del_compra', name='del_venta'),
    url(r'^entrada/detalles$', 'entrada_mercancia.views.detalle_compra', name='detalle_compra'),
   # urls-registo de ventas
    url(r'^registro-ventas/$', 'registro_venta.views.registro_ventas', name='registro_ventas'),
   # urls-resumen de movimientos
    url(r'^resumen-movimientos/$', 'resumen_movimientos.views.resumen_mov', name='resumen_mov'),
    url(r'^resumen-movimientos/export-excel$', 'resumen_movimientos.views.export_excel'),
    url(r'^resumen-movimientos/export-pdf$', 'resumen_movimientos.views.export_pdf'),
   # urls-reporte de movimientos de productos
    url(r'^reporte-movimientos-productos/$', 'resumen_movimientos_prod.views.resumen_mov', name='resumen_mov'),
    url(r'^reporte-movimientos-productos/export-excel$', 'resumen_movimientos_prod.views.export_excel'),
    url(r'^reporte-movimientos-productos/export-pdf$', 'resumen_movimientos_prod.views.export_pdf'),
   # urls-stock disponible
    url(r'^stock-disponible/$', 'stock_disponible.views.stock_disponible', name='stock_disponible'),
    url(r'^stock-disponible/export-excel$', 'stock_disponible.views.export_excel'),
    url(r'^stock-disponible/export-pdf$', 'stock_disponible.views.export_pdf'),
   # urls-resumen de ventas
    url(r'^resumen-ventas/$', 'resumen_ventas.views.resumen_venta', name='resumen_venta'),
    url(r'^resumen-ventas/detalles$', 'resumen_ventas.views.detalle_venta', name='detalle_venta'),
   # urls-resumen de compra
    url(r'^resumen-compras/$', 'resumen_compras.views.resumen_compra', name='resumen_compra'),
    url(r'^resumen-compras/detalles$', 'resumen_compras.views.detalle_compra', name='detalle_compra'),
   # urls-reportes cliente
    url(r'^reporte-cliente-diario/$', 'reportes_cliente.views.reporte_cliente', {"tipo": "diario"}),
    url(r'^reporte-cliente-mensual/$', 'reportes_cliente.views.reporte_cliente', {"tipo": "mensual"}),
    url(r'^reporte-cliente-anual/$', 'reportes_cliente.views.reporte_cliente', {"tipo": "anual"}),
    url(r'^reporte-cliente/export-excel$', 'reportes_cliente.views.export_excel'),
    url(r'^reporte-cliente/export-pdf$', 'reportes_cliente.views.export_pdf'),
   # urls-reportes proveedor
    url(r'^reporte-proveedor-diario/$', 'reportes_proveedor.views.reporte_proveedor', {"tipo": "diario"}),
    url(r'^reporte-proveedor-mensual/$', 'reportes_proveedor.views.reporte_proveedor', {"tipo": "mensual"}),
    url(r'^reporte-proveedor-anual/$', 'reportes_proveedor.views.reporte_proveedor', {"tipo": "anual"}),
    url(r'^reporte-proveedor/export-excel$', 'reportes_proveedor.views.export_excel'),
    url(r'^reporte-proveedor/export-pdf$', 'reportes_proveedor.views.export_pdf'),
)

urlpatterns += patterns('',
    url(r'^admin/', include(admin.site.urls)),
)

control_inventario/models.py
from pickle import TRUE
from django.db import models
from django.contrib.auth.models import User


class Empresa(models.Model):
    nombre = models.CharField(max_length=30)
    direccion = models.CharField(max_length=50)
    anno_inicio = models.IntegerField()
    ruc = models.IntegerField(unique=TRUE)
    user = models.ManyToManyField(User)


class Categoria(models.Model):
    codigo = models.IntegerField(unique=TRUE)
    denominacion = models.CharField(max_length=50)
    empresa = models.ForeignKey(Empresa)

    def __str__(self):
        return self.denominacion


class TipoProducto(models.Model):
    codigo = models.IntegerField(unique=TRUE)
    denominacion = models.CharField(max_length=50)

    def __str__(self):
        return self.denominacion

    class Admin:
        pass


class UnidadProducto(models.Model):
    codigo = models.IntegerField(unique=TRUE)
    denominacion = models.CharField(max_length=50)
    abreviatura = models.CharField(max_length=10)

    def __str__(self):
        return self.denominacion

    class Admin:
        pass


class Producto(models.Model):
    codigo = models.IntegerField(unique=TRUE)
    nombre = models.CharField(max_length=30)
    nombre_reducido = models.CharField(max_length=30)
    tipo = models.ForeignKey(TipoProducto)
    unidad = models.ForeignKey(UnidadProducto)
    categoria = models.ForeignKey(Categoria)
    empresa = models.ForeignKey(Empresa)


class TipoId(models.Model):
    codigo = models.IntegerField(unique=TRUE)
    denominacion = models.CharField(max_length=50)

    def __str__(self):
        return self.denominacion

    class Admin:
        pass


class Proveedor(models.Model):
    nombre = models.CharField(max_length=30)
    direccion = models.CharField(max_length=50)
    identificador = models.IntegerField(unique=TRUE)
    tipo_id = models.ForeignKey(TipoId)
    empresa = models.ForeignKey(Empresa)


class Cliente(models.Model):
    nombre = models.CharField(max_length=30)
    direccion = models.CharField(max_length=50)
    identificador = models.IntegerField(unique=TRUE)
    tipo_id = models.ForeignKey(TipoId)
    empresa = models.ForeignKey(Empresa)


class Inventario(models.Model):
    costo_unitario = models.DecimalField(decimal_places=4, max_digits=6)
    cantidad = models.IntegerField()
    producto = models.ForeignKey(Producto)
    empresa = models.ForeignKey(Empresa)


class InventarioHist(models.Model):
    fecha_real = models.DateField()
    fecha_operacion = models.DateField()
    tipo_operacion = models.CharField(max_length=10)
    cantidad = models.IntegerField()
    cantidad_final = models.IntegerField()
    producto = models.ForeignKey(Producto)
    empresa = models.ForeignKey(Empresa)



class TipoComprobante(models.Model):
    codigo = models.IntegerField()
    denominacion = models.CharField(max_length=50)


class Compra(models.Model):
    fecha = models.DateField()
    serie = models.IntegerField()
    numero = models.IntegerField()
    tipo_comprobante = models.ForeignKey(TipoComprobante)
    subtotal = models.DecimalField(max_digits=6, decimal_places=2)
    igv = models.DecimalField(max_digits=6, decimal_places=2)
    total = models.DecimalField(max_digits=6, decimal_places=2)
    proveedor = models.ForeignKey(Proveedor)
    empresa = models.ForeignKey(Empresa)


class DetalleCompra(models.Model):
    descripcion = models.CharField(max_length=255)
    cantidad = models.IntegerField()
    valor_unitario = models.DecimalField(max_digits=6, decimal_places=2)
    valor_venta = models.DecimalField(max_digits=6, decimal_places=2)
    igv = models.DecimalField(max_digits=6, decimal_places=2)
    importe = models.DecimalField(max_digits=6, decimal_places=2)
    producto = models.ForeignKey(Producto)
    compra = models.ForeignKey(Compra)


class Venta(models.Model):
    fecha = models.DateField()
    serie = models.IntegerField()
    numero = models.IntegerField()
    tipo_comprobante = models.ForeignKey(TipoComprobante)
    subtotal = models.DecimalField(max_digits=6, decimal_places=2)
    igv = models.DecimalField(max_digits=6, decimal_places=2)
    total = models.DecimalField(max_digits=6, decimal_places=2)
    cliente = models.ForeignKey(Cliente)
    empresa = models.ForeignKey(Empresa)


class DetalleVenta(models.Model):
    descripcion = models.CharField(max_length=255)
    cantidad = models.IntegerField()
    valor_unitario = models.DecimalField(max_digits=6, decimal_places=2)
    valor_venta = models.DecimalField(max_digits=6, decimal_places=2)
    igv = models.DecimalField(max_digits=6, decimal_places=2)
    importe = models.DecimalField(max_digits=6, decimal_places=2)
    producto = models.ForeignKey(Producto)
    venta = models.ForeignKey(Venta)


class TipoOperacion(models.Model):
    denominacion = models.CharField(max_length=50)


class EstadoPLE(models.Model):
    denominacion = models.CharField(max_length=50)

control_inventario/app/categoria/views.py
from django.shortcuts import render_to_response, redirect
from django.template import RequestContext
from django.http import HttpResponseRedirect, HttpResponse
from django.core.context_processors import csrf
from control_inventario import forms, models
import json
# users
from django.contrib.auth.decorators import login_required


# --------- Categoria ----------
@login_required(login_url='/ingresar')
def categoria(request):
    id_empresa = request.session['empresa']["id"]
    emp = models.Empresa.objects.get(id=id_empresa)
    datos = request.POST
    args = {}
    args['categoria_list'] = emp.categoria_set.values()

    if datos:
        if datos.get("id"):
            cat = emp.categoria_set.get(id=datos.get("id"))
            cat.codigo = datos.get("codigo")
            cat.denominacion = datos.get("denominacion")
            cat.save()
            args['action'] = 'mod'
        else:
            cat = models.Categoria(
                codigo=datos.get("codigo"),
                denominacion=datos.get("denominacion"),
                empresa=emp
            )
            cat.save()
            args['action'] = 'add'

    if request.session.has_key("categoria-del") == 1:
        if request.session["categoria-del"]:
            args['action'] = 'del'
            request.session["categoria-del"] = False

    args.update(csrf(request))
    return render_to_response('categoria/main.html', args, context_instance=RequestContext(request))


@login_required(login_url='/ingresar')
def del_categoria(request):
    categoria = models.Categoria.objects.get(id=request.POST.get("id"))
    categoria.delete()
    request.session['categoria-del'] = True

    args = {}
    args['success'] = True
    json_data = json.dumps(args)
    return HttpResponse(json_data, mimetype="application/json")

control_inventario/app/cliente/views.py
from django.shortcuts import render_to_response, redirect
from django.template import RequestContext
from django.http import HttpResponseRedirect, HttpResponse
from django.core.context_processors import csrf
from control_inventario import forms, models
from django.contrib.auth.decorators import login_required
import json


def list_cliente(cliente_list):
    for ciente in cliente_list:
        ciente["tipo_id"] = models.TipoId.objects.get(id=ciente.get("tipo_id_id"))
    return cliente_list


@login_required(login_url='/ingresar')
def cliente(request):
    id_empresa = request.session['empresa']["id"]
    emp = models.Empresa.objects.get(id=id_empresa)
    c = emp.cliente_set.values()

    tipoid_list = models.TipoId.objects.values()

    args = {}
    datos = request.POST
    if datos:
        tipo_id = models.TipoId.objects.get(id=datos.get("tipo_id"))
        if datos.get("id"):
            p = models.Cliente(
                id=datos.get("id"),
                identificador=datos.get("identificador"),
                nombre=datos.get("nombre"),
                direccion=datos.get("direccion"),
                tipo_id=tipo_id,
                empresa=emp
            )
            p.save()
            args['action'] = 'mod'
        else:
            p = models.Cliente(
                identificador=datos.get("identificador"),
                nombre=datos.get("nombre"),
                direccion=datos.get("direccion"),
                tipo_id=tipo_id,
                empresa=emp
            )
            p.save()
            args['action'] = 'add'

    if request.session.has_key("cliente-del") == 1:
        if request.session["cliente-del"]:
            args['action'] = 'del'
            request.session["cliente-del"] = False

    cliente_list = list_cliente(c)
    args.update(csrf(request))
    args['cliente_list'] = cliente_list
    args['tipoid_list'] = tipoid_list
    render_to_response('clientes/form-cliente.html', args)
    return render_to_response('clientes/main.html', args, context_instance=RequestContext(request))


@login_required(login_url='/ingresar')
def del_cliente(request):
    cliente = models.Cliente.objects.get(id=request.POST.get("id"))
    cliente.delete()
    request.session['cliente-del'] = True

    args = {}
    args['success'] = True
    json_data = json.dumps(args)
    return HttpResponse(json_data, mimetype="application/json")

control_inventario/app/empresa/views.py
from django.shortcuts import render_to_response, redirect
from django.template import RequestContext
from django.http import HttpResponseRedirect, HttpResponse
from django.core.context_processors import csrf
from control_inventario import forms, models
import json
# users
from django.contrib.auth.decorators import login_required


@login_required(login_url='/ingresar')
def empresa(request):
    empresa_list = models.Empresa.objects.values()
    datos = request.POST
    args = {}

    if datos:
        if datos.get("id"):
            emp = models.Empresa.objects.get(id=datos.get("id"))
            emp.nombre = datos.get("nombre")
            emp.anno_inicio = datos.get("anno_inicio")
            emp.ruc = datos.get("ruc")
            emp.direccion = datos.get("direccion")
            emp.save()
            args['action'] = "mod"
        else:
            form = forms.EmpresaForm(request.POST)
            if form.is_valid():
                args['action'] = "add"
                form.save()
            else:
                args['action'] = "error"

    if request.session.has_key("empresa-del") == 1:
        if request.session["empresa-del"]:
            args['action'] = 'del'
            request.session["empresa-del"] = False
    args.update(csrf(request))
    args['empresa_list'] = empresa_list
    return render_to_response('empresa/main.html', args, context_instance=RequestContext(request))


def select_empresa(request):
    datos = request.POST
    request.session['empresa'] = {
        "ruc": datos.get("empresa[ruc]"),
        "nombre": datos.get("empresa[nombre]"),
        "id": datos.get("empresa[id]"),
        "direccion": datos.get("empresa[direccion]"),
        "anno_inicio": datos.get("empresa[anno_inicio]"),
    }
    request.session['mes'] = datos.get("mes")
    json_data = json.dumps({"success": True})
    return HttpResponse(json_data, mimetype="application/json")


@login_required(login_url='/ingresar')
def del_empresa(request):
    empresa = models.Empresa.objects.get(id=request.POST.get("id"))
    empresa.delete()
    request.session['empresa-del'] = True

    args = {}
    args['success'] = True
    json_data = json.dumps(args)
    return HttpResponse(json_data, mimetype="application/json")


def select_periodo(request):
    request.session['mes'] = request.POST.get("periodo")
    return HttpResponseRedirect('/')

control_inventario/app/registro_venta/views.py
from django.shortcuts import render_to_response
from django.template import RequestContext
from control_inventario import models
from django.contrib.auth.decorators import login_required


@login_required(login_url='/ingresar')
def registro_ventas(request):
    id_empresa = request.session['empresa']["id"]
    emp = models.Empresa.objects.get(id=id_empresa)

    estadoPLE_list = models.EstadoPLE.objects.values()
    comprobante_list = models.TipoComprobante.objects.values()
    cliente_list = emp.cliente_set.values()

    args = {}
    args['estadoPLE_list'] = estadoPLE_list
    args['cliente_list'] = cliente_list
    args['comprobante_list'] = comprobante_list
    return render_to_response('registro_ventas/main.html', args, context_instance=RequestContext(request))

control_inventario/templates/categoria/categoria.html
{% extends "index.html" %}

{% block title %}
    Categoria
{% endblock %}

{% block content %}
    <div class="modal fade confirm-del" tabindex="-1" role="dialog" aria-labelledby="mySmallModalLabel"
         aria-hidden="true">
        <div class="modal-dialog modal-xs">
            <div class="modal-content">
                <div class="modal-header">
                    <button data-dismiss="modal" class="close" type="button"><span aria-hidden="true">×</span><span
                            class="sr-only">Close</span></button>
                    <h4 id="mySmallModalLabel" class="modal-title">Eliminar categor&iacute;a</h4>
                </div>
                <div class="modal-body">
                    <form action="del" method="post" id="del-table" accion="del">
                        {% csrf_token %}
                        <input type="text" name="codigo" class="hidden">

                        <p>Est&aacute; seguro que desea eliminar la categor&iacute;a seleccionada</p>

                        <div class="btn-modals">
                            <button class="btn btn-default" data-dismiss="modal">Cerrar</button>
                            <button class="btn btn-primary" type="submit">Aceptar</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
    <div class="col-md-10 col-md-offset-1">
        <!-- Modal -->
        <div class="modal fade" id="form-categoria" tabindex="-1" role="dialog" aria-labelledby="form-categoriaLabel"
             aria-hidden="true">
            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span
                                class="sr-only">Close</span></button>
                        <h4 class="modal-title" id="form-categoria-label">Adicionar categoria</h4>
                    </div>
                    <div class="modal-body">
                        {% include "categoria/form-categoria.html" %}
                    </div>
                </div>
            </div>
        </div>
        <!-- /horizotal form -->
        {#        Tabla categorias#}
        {% include "categoria/table-categoria.html" %}
    </div>
    {#    {{ categoria_list }}#}
{% endblock %}

control_inventario/templates/categoria/form-categoria.html
<div class="modal fade in" id="form-categoria">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header bg-primary">
                <h6 class="modal-title" id="form-categoria-label">Adicionar categor&iacute;a</h6>
            </div>

            <form class="form-horizontal" enctype="multipart/form-data" method="post" action="" novalidate
                  table="tabla-categoria">
                <div class="modal-body">
                    {% csrf_token %}
                    <input type="text" name="id" value="" class="hidden">
                    <input type="text" name="id_empresa" value="" class="hidden">
                    {#Codigo#}
                    <div class="form-group">
                        <label class="control-label col-lg-1">C&oacute;digo</label>

                        <div class="col-lg-4">
                            <input type="text" name="codigo" class="form-control" required numberfield>
                        </div>
                        {#Denominacion#}
                        <label class="control-label col-lg-2">Denominaci&oacute;n</label>

                        <div class="col-lg-5">
                            <input type="text" name="denominacion" id="id_denominacion" class="form-control" required>
                        </div>
                    </div>

                </div>
                <div class="modal-footer">
                    <button class="btn btn-default" data-dismiss="modal">
                        Cerrar
                    </button>
                    <button class="btn btn-primary" type="submit">Guardar</button>
                </div>
            </form>
        </div>
    </div>
</div>

control_inventario/templates/categoria/main.html
{% extends "index.html" %}
{% load staticfiles %}

{% block script %}
    <script src="{% static 'js/limitless/plugins/notifications/bootbox.min.js' %}" type="text/javascript"></script>
    <script src="{% static 'js/limitless/plugins/notifications/sweet_alert.min.js' %}" type="text/javascript"></script>
    <script src="{% static 'js/limitless/core/app.js' %}" type="text/javascript"></script>
    <script src="{% static 'js/app/categoria/functions.js' %}" type="text/javascript"></script>
{% endblock %}

{% block title %}
    Categor&iacute;a
{% endblock %}

{% block content %}
    {% if action == "add" %}
        <script type="text/javascript">
            showMsg("La categor&iacute;a se ha adicionado satisfactoriamente")
        </script>
    {% endif %}
    {% if action == "mod" %}
        <script type="text/javascript">
            showMsg("La categor&iacute;a se ha modificado satisfactoriamente")
        </script>
    {% endif %}
    {% if action == "del" %}
        <script type="text/javascript">
            showMsg("La categor&iacute;a se ha eliminado satisfactoriamente")
        </script>
    {% endif %}

    {#    Form categorias#}
    {% include "categoria/form-categoria.html" %}
    {#        Tabla categorias#}
    {% include "categoria/table-categoria.html" %}
{% endblock %}

control_inventario/templates/categoria/table-categoria.html
<div class="panel panel-primary panel-bordered">
    <div class="panel-heading">
        <h6 class="panel-title">Lista de categor&iacute;as</h6>

        <div class="heading-elements">
            <ul class="icons-list">
                <li><a title="Adicionar (CTR+A)" action="add-categoria"><i class=" icon-plus-circle2"></i></a></li>
                <li class="disabled" table="tabla-categoria"><a title="Editar (CTR+M)" action="mod-categoria"><i class="icon-pen6"></i></a></li>
                <li class="disabled" table="tabla-categoria"><a title="Eliminar (DEL)" action="del-categoria"><i class="icon-trash"></i></a></li>
            </ul>
        </div>
        <a class="heading-elements-toggle"><i class="icon-menu"></i></a></div>

    <div class="panel-body">
        <table class="table table-hover table-bordered" id="tabla-categoria" select="true">
            <thead class="bg-primary-600">
            <tr>
                <th class="hidden">id</th>
                <th>C&oacute;digo</th>
                <th>Denominaci&oacute;n</th>
            </tr>
            </thead>
            <tbody>
            {% if categoria_list %}
                {% for categoria in categoria_list %}
                    <tr>
                        <td name="id" class="hidden">{{ categoria.id }}</td>
                        <td name="codigo">{{ categoria.codigo }}</td>
                        <td name="denominacion">{{ categoria.denominacion }}</td>
                    </tr>
                {% endfor %}
            {% endif %}
            </tbody>
        </table>
    </div>
</div>